### ISSUE TITLE
Is the project active?

### ISSUE THREAD

**Issue by aghasemi** [jabbalaci/PyJava#2]
Hi,
I can help with adding some numpy functions that I have implemented for my research work. Is the project still active?

**Comment by jabbalaci** [comment]
Hi,
Thanks, but the project is not active. It was a fun project for a week or two but I don't think I'll ever use it in a larger Java project. I don't want to spend more time with this.
Best,
Laszlo

**Comment by jabbalaci** [comment]
I started to play with Kotlin two weeks ago and this is what I was looking for. So instead of using this project, just use Kotlin. It works together with Java and it's very similar to Python.
