### ISSUE TITLE
same problem solved

### ISSUE THREAD

**Issue by rsharifnasab** [jabbalaci/PyJava#3]
hi, first of all i should mention that i dont have any problem i just want to thank you
i had same problem as you, i was a python programmer that i had to write java programs 
i was thinking about developing a library to help me 
so i chose pyJava name and created an empty repository
then i searched about same projects and found your project
i'm really happy and thankful :))

**Comment by jabbalaci** [comment]
Thanks for the feedback. I can suggest Kotlin, this project is not maintained. If you come from Python, you'll like Kotlin.

**Comment by rsharifnasab** [comment]
thank you for suggesting
I'll take a look at Kotlin too
